//! Start/finish-line crossing detection for recordings (game-awareness 1.6 +
//! 1.7: "the timer under From: should be from when it crosses the start
//! line", "if the player crosses the finish line during record, the
//! recording should stop").
//!
//! The game's race timer starts/ends at TRIGGER PLANES (Start_Point /
//! Finish_Point markers), already extracted offline into
//! `analyze/src/LevelData/levelData.json`; the tables below are generated
//! from it (`TAS/tools/gen_start_lines.py`, `gen_finish_lines.py`).
//!
//! Geometry: on all nine tracks the course coordinates rise monotonically in
//! BOTH y and z from start to finish, with z the dominant axis (Δz ≈ +2200 vs
//! Δy ≈ +1100 over a run), so a crossing is detected as "z rises past the
//! trigger's z" gated to the plane's lateral (x) extent. Tracks with several
//! points for one line (a wide line, or course variants) cross on ANY point;
//! the start picks the point nearest the spawn first.

/// Trigger plane half-extent (engine constant, from the line-geometry RE).
const PLANE_RADIUS: f32 = 90.5;

/// Per-track `Start_Point` trigger centers, keyed by level code.
/// Generated by `TAS/tools/gen_start_lines.py` — do not hand-edit.
pub const START_POINTS: &[(&str, &[[f32; 3]])] = &[
    ("AE", &[[645.168, -831.709, 110.084]]),
    ("AH", &[[645.168, -831.709, 110.084]]),
    ("AM", &[[645.168, -831.709, 110.084]]),
    (
        "FE",
        &[[519.368, -1384.164, 99.782], [412.575, -232.188, -64.914]],
    ),
    (
        "FH",
        &[[518.553, -1535.384, 99.917], [412.575, -257.286, -64.914]],
    ),
    (
        "FM",
        &[[518.553, -1535.384, 99.917], [412.575, -257.286, -64.914]],
    ),
    ("VE", &[[729.527, -457.721, 231.772]]),
    ("VH", &[[439.386, -501.646, 114.804]]),
    ("VM", &[[801.000, -481.165, 299.284]]),
];

/// Per-track `Finish_Point` trigger centers, keyed by level code.
/// Generated by `TAS/tools/gen_finish_lines.py` — do not hand-edit.
/// VM carries three points spanning the line's width.
pub const FINISH_POINTS: &[(&str, &[[f32; 3]])] = &[
    ("AE", &[[620.691, 372.302, 2_564.11]]),
    ("AH", &[[1_119.88, 543.207, 2_291.78]]),
    ("AM", &[[620.712, 372.308, 2_564.13]]),
    ("FE", &[[534.888, -284.278, 2_313.64]]),
    ("FH", &[[543.770, -304.486, 2_340.92]]),
    ("FM", &[[543.770, -304.486, 2_340.92]]),
    ("VE", &[[430.776, 738.915, 2_657.77]]),
    ("VH", &[[211.158, 292.066, 1_897.36]]),
    (
        "VM",
        &[
            [605.560, 1014.658, 2_583.45],
            [562.330, 1013.058, 2_580.01],
            [661.130, 1013.058, 2_589.11],
        ],
    ),
];

/// Per-level spawn-cluster centroids (Player_Start_Location), generated by
/// `TAS/tools/gen_spawn_points.py`. NOTE the shared clusters: AE/AM/AH spawn
/// at the same point, as do FM/FH — a spawn match within those groups is
/// AMBIGUOUS and must not produce a single level code.
pub const SPAWN_CENTROIDS: &[(&str, [f32; 3])] = &[
    ("AE", [642.890, -842.161, 96.513]),
    ("AH", [642.890, -842.161, 96.513]),
    ("AM", [642.890, -842.161, 96.513]),
    ("FE", [519.968, -1401.603, 53.645]),
    ("FH", [519.968, -1554.112, 53.645]),
    ("FM", [519.968, -1554.112, 53.645]),
    ("VE", [728.664, -461.080, 225.150]),
    ("VH", [441.358, -513.598, 94.347]),
    ("VM", [800.886, -484.151, 291.386]),
];

/// Spawn-match radius: clusters are ~10 units wide; the closest DISTINCT
/// centroids (VE-VM) are 100.7 apart, so 40 has wide margins both ways.
const SPAWN_MATCH_RADIUS: f32 = 40.0;

/// Classify a recording's level from its spawn position (rec_coords[0]).
/// Returns the level code only when the spawn maps to exactly ONE level —
/// recordings on the shared Alpine / Forest-Med-Hard clusters return None
/// (ambiguous) rather than a guess. Used to backfill the level tag on
/// history entries persisted before tagging existed.
pub fn level_code_from_spawn(pos: &[f32; 3]) -> Option<&'static str> {
    let r_sq = SPAWN_MATCH_RADIUS * SPAWN_MATCH_RADIUS;
    let mut matches: Vec<&'static str> = Vec::new();
    for (code, c) in SPAWN_CENTROIDS {
        let dx = pos[0] - c[0];
        let dy = pos[1] - c[1];
        let dz = pos[2] - c[2];
        if dx * dx + dy * dy + dz * dz <= r_sq {
            matches.push(code);
        }
    }
    match matches.as_slice() {
        [one] => Some(one),
        _ => None, // no match, or a shared (ambiguous) cluster
    }
}

fn points_for(
    table: &'static [(&'static str, &'static [[f32; 3]])],
    code: &str,
) -> Option<&'static [[f32; 3]]> {
    table.iter().find(|(c, _)| *c == code).map(|(_, p)| *p)
}

fn dist_sq_xz(a: &[f32; 3], b: &[f32; 3]) -> f32 {
    let dx = a[0] - b[0];
    let dz = a[2] - b[2];
    dx * dx + dz * dz
}

/// First tick in `[from..n)` whose z rises past any of `points`' z, within the
/// plane's lateral (x) extent of that point.
fn cross_tick_z(
    rec_coords: &[[f32; 3]],
    n: usize,
    from: usize,
    points: &[[f32; 3]],
) -> Option<u32> {
    for i in from.max(1)..n {
        let prev = &rec_coords[i - 1];
        let cur = &rec_coords[i];
        for p in points {
            if prev[2] < p[2] && cur[2] >= p[2] && (cur[0] - p[0]).abs() <= PLANE_RADIUS {
                return Some(i as u32);
            }
        }
    }
    None
}

/// The tick at which the recording crosses the start line, i.e. when the
/// in-game race timer starts. `None` when the level is unknown, has no start
/// point, or the recording never crosses (bailed before the gate).
pub fn start_cross_tick(
    rec_coords: &[[f32; 3]],
    recorded_count: u32,
    level_code: Option<&str>,
) -> Option<u32> {
    let code = level_code?;
    let points = points_for(START_POINTS, code)?;
    let n = (recorded_count as usize).min(rec_coords.len());
    if n < 2 {
        return None;
    }
    // Multiple Start_Points on a track = course variants; the relevant gate is
    // the one nearest the spawn (first recorded position).
    let spawn = &rec_coords[0];
    let sp = points.iter().min_by(|a, b| {
        dist_sq_xz(a, spawn)
            .partial_cmp(&dist_sq_xz(b, spawn))
            .unwrap_or(std::cmp::Ordering::Equal)
    })?;
    cross_tick_z(rec_coords, n, 1, std::slice::from_ref(sp))
}

/// The tick at which the recording crosses the FINISH line (any of the
/// track's finish points), scanning from `from` (a cursor so live polling
/// only examines new ticks). `None` when unknown level / no cross yet.
pub fn finish_cross_tick(
    rec_coords: &[[f32; 3]],
    recorded_count: u32,
    level_code: Option<&str>,
    from: u32,
) -> Option<u32> {
    let code = level_code?;
    let points = points_for(FINISH_POINTS, code)?;
    let n = (recorded_count as usize).min(rec_coords.len());
    if n < 2 {
        return None;
    }
    cross_tick_z(rec_coords, n, from as usize, points)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Synthetic FE-like run: stationary spawn, then ride +y/+z past the gate.
    fn fe_run() -> Vec<[f32; 3]> {
        let mut v = Vec::new();
        for _ in 0..50 {
            v.push([519.2, -1401.6, 53.6]);
        }
        // Ride: z +1.5/tick, y +0.5/tick (z dominant, like the real course).
        for i in 0..2000 {
            let t = i as f32 + 1.0;
            v.push([519.2 + (t * 0.01), -1401.6 + 0.5 * t, 53.6 + 1.5 * t]);
        }
        v
    }

    #[test]
    fn detects_fe_start_after_first_moving() {
        let coords = fe_run();
        let tick = start_cross_tick(&coords, coords.len() as u32, Some("FE")).unwrap();
        // Crossing must be AFTER the 50-tick stationary prefix (first_moving)
        // and at the gate's z (99.782).
        assert!(tick > 50, "crossed at {}", tick);
        assert!(coords[tick as usize][2] >= 99.782);
        assert!(coords[tick as usize - 1][2] < 99.782);
    }

    #[test]
    fn picks_nearest_start_point_of_variants() {
        // FE's second far-away Start_Point sits at x=412.575 — 100+ units off
        // this run's x, so only the (519, .., 99.78) gate may fire.
        let coords = fe_run();
        let tick = start_cross_tick(&coords, coords.len() as u32, Some("FE")).unwrap();
        assert!((coords[tick as usize][2] - 99.782).abs() < 2.0);
    }

    #[test]
    fn detects_fe_finish_and_cursor_resumes() {
        let coords = fe_run();
        let n = coords.len() as u32;
        let finish = finish_cross_tick(&coords, n, Some("FE"), 0).unwrap();
        // FE finish z = 2313.64 → (2313.64 - 53.6) / 1.5 ≈ tick 1507 + 50.
        assert!(coords[finish as usize][2] >= 2313.64);
        assert!(coords[finish as usize - 1][2] < 2313.64);
        // Scanning from past the crossing finds nothing (cursor semantics).
        assert_eq!(finish_cross_tick(&coords, n, Some("FE"), finish + 1), None);
    }

    #[test]
    fn none_when_level_unknown_or_no_cross() {
        let coords = fe_run();
        assert_eq!(start_cross_tick(&coords, coords.len() as u32, None), None);
        let short: Vec<[f32; 3]> = coords[..60].to_vec();
        assert_eq!(start_cross_tick(&short, 60, Some("FE")), None);
        assert_eq!(finish_cross_tick(&short, 60, Some("FE"), 0), None);
    }

    #[test]
    fn off_line_crossing_outside_radius_does_not_count() {
        // Crossing the gate's z but 200 units off in x must not register.
        let mut v = Vec::new();
        for i in 0..200 {
            v.push([519.2 + 200.0, -1401.6, 53.6 + 1.5 * (i as f32)]);
        }
        assert_eq!(start_cross_tick(&v, 200, Some("FE")), None);
    }

    #[test]
    fn vm_wide_finish_crosses_on_any_point() {
        // A run down VM's left edge (x ≈ 562) crosses the wide finish via its
        // second point even though it's 40+ units from the center point.
        let mut v = Vec::new();
        for i in 0..3000 {
            v.push([562.3, -481.0 + (i as f32), 299.0 + (i as f32)]);
        }
        let t = finish_cross_tick(&v, 3000, Some("VM"), 0);
        assert!(t.is_some());
    }

    #[test]
    fn spawn_classifier_tags_unique_spawns_only() {
        // FE spawn → FE.
        assert_eq!(level_code_from_spawn(&[519.2, -1401.6, 53.6]), Some("FE"));
        // Village spawns are all unique.
        assert_eq!(level_code_from_spawn(&[728.7, -461.1, 225.2]), Some("VE"));
        assert_eq!(level_code_from_spawn(&[441.4, -513.6, 94.3]), Some("VH"));
        assert_eq!(level_code_from_spawn(&[800.9, -484.2, 291.4]), Some("VM"));
        // The Alpine trio SHARES a spawn — must refuse to guess.
        assert_eq!(level_code_from_spawn(&[642.9, -842.2, 96.5]), None);
        // FM/FH share — refuse.
        assert_eq!(level_code_from_spawn(&[519.9, -1554.1, 53.6]), None);
        // Nowhere near any spawn.
        assert_eq!(level_code_from_spawn(&[0.0, 0.0, 0.0]), None);
    }

    #[test]
    fn all_nine_tracks_have_start_and_finish() {
        for code in ["FE", "FM", "FH", "AE", "AM", "AH", "VE", "VM", "VH"] {
            assert!(points_for(START_POINTS, code).is_some_and(|p| !p.is_empty()));
            assert!(points_for(FINISH_POINTS, code).is_some_and(|p| !p.is_empty()));
        }
    }
}
