//! Start-line crossing detection for recordings (game-awareness 1.6 / "the
//! timer under From: should be from when it crosses the start line").
//!
//! The game's race timer starts when the player crosses the START LINE — a
//! trigger plane ~10–20 units down-course of the spawn — NOT when the boarder
//! first moves (`first_moving`, which fires at the countdown end, 0.5–3 s
//! before the line). The per-track `Start_Point` trigger centers are already
//! extracted offline into `analyze/src/LevelData/levelData.json`; the table
//! below is generated from it (`TAS/tools/gen_start_lines.py`). Every track's
//! course runs +Y at the gate (verified across all nine), so the crossing is
//! "first tick where Y rises past the nearest start point", gated to the
//! trigger plane's horizontal radius.

/// Trigger plane half-extent (engine constant, from the line-geometry RE).
const PLANE_RADIUS: f32 = 90.5;

/// Per-track `Start_Point` trigger centers, keyed by level code.
/// Generated by `TAS/tools/gen_start_lines.py` from levelData.json — do not
/// hand-edit. Some tracks carry a second far-away point (course variant);
/// `start_cross_tick` picks the one nearest the recording's spawn.
pub const START_POINTS: &[(&str, &[[f32; 3]])] = &[
    ("AE", &[[645.168, -831.709, 110.084]]),
    ("AH", &[[645.168, -831.709, 110.084]]),
    ("AM", &[[645.168, -831.709, 110.084]]),
    ("FE", &[[519.368, -1384.164, 99.782], [412.575, -232.188, -64.914]]),
    ("FH", &[[518.553, -1535.384, 99.917], [412.575, -257.286, -64.914]]),
    ("FM", &[[518.553, -1535.384, 99.917], [412.575, -257.286, -64.914]]),
    ("VE", &[[729.527, -457.721, 231.772]]),
    ("VH", &[[439.386, -501.646, 114.804]]),
    ("VM", &[[801.000, -481.165, 299.284]]),
];

fn dist_sq_xz(a: &[f32; 3], b: &[f32; 3]) -> f32 {
    let dx = a[0] - b[0];
    let dz = a[2] - b[2];
    dx * dx + dz * dz
}

/// The tick at which the recording crosses the start line, i.e. when the
/// in-game race timer starts. `None` when the level is unknown, has no start
/// point, or the recording never crosses (bailed before the gate).
pub fn start_cross_tick(
    rec_coords: &[[f32; 3]],
    recorded_count: u32,
    level_code: Option<&str>,
) -> Option<u32> {
    let code = level_code?;
    let points = START_POINTS
        .iter()
        .find(|(c, _)| *c == code)
        .map(|(_, p)| *p)?;
    let n = (recorded_count as usize).min(rec_coords.len());
    if n < 2 {
        return None;
    }
    // Multiple Start_Points on a track = course variants; the relevant gate is
    // the one nearest the spawn (first recorded position).
    let spawn = &rec_coords[0];
    let sp = points
        .iter()
        .min_by(|a, b| {
            dist_sq_xz(a, spawn)
                .partial_cmp(&dist_sq_xz(b, spawn))
                .unwrap_or(std::cmp::Ordering::Equal)
        })?;

    let r_sq = PLANE_RADIUS * PLANE_RADIUS;
    for i in 1..n {
        let prev = &rec_coords[i - 1];
        let cur = &rec_coords[i];
        // Course direction at the gate is +Y on every track: a rising crossing
        // of the trigger's Y, within the plane's horizontal extent.
        if prev[1] < sp[1] && cur[1] >= sp[1] && dist_sq_xz(cur, sp) <= r_sq {
            return Some(i as u32);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Synthetic FE-like run: spawn below the gate, ride +Y past it.
    fn fe_run() -> Vec<[f32; 3]> {
        let mut v = Vec::new();
        // Stationary spawn (countdown) at the real FE spawn.
        for _ in 0..50 {
            v.push([519.2, -1401.6, 53.6]);
        }
        // Ride +Y, 0.5 units/tick: crosses y=-1384.164 about 35 ticks in.
        for i in 0..100 {
            v.push([519.2, -1401.6 + 0.5 * (i as f32 + 1.0), 53.6]);
        }
        v
    }

    #[test]
    fn detects_fe_crossing_after_first_moving() {
        let coords = fe_run();
        let tick = start_cross_tick(&coords, coords.len() as u32, Some("FE")).unwrap();
        // Crossing must be AFTER the 50-tick stationary prefix (first_moving).
        assert!(tick > 50, "crossed at {}", tick);
        // y at the crossing tick must be at/above the gate.
        assert!(coords[tick as usize][1] >= -1384.164);
        assert!(coords[tick as usize - 1][1] < -1384.164);
    }

    #[test]
    fn picks_nearest_start_point_of_variants() {
        // FE has a second far-away Start_Point at (412, -232, -64); a run from
        // the normal spawn must use the (519, -1384) gate, not cross at -232.
        let coords = fe_run();
        let tick = start_cross_tick(&coords, coords.len() as u32, Some("FE")).unwrap();
        assert!((coords[tick as usize][1] - -1384.164).abs() < 1.0);
    }

    #[test]
    fn none_when_level_unknown_or_no_cross() {
        let coords = fe_run();
        assert_eq!(start_cross_tick(&coords, coords.len() as u32, None), None);
        // A run that never reaches the gate:
        let short: Vec<[f32; 3]> = coords[..60].to_vec();
        assert_eq!(start_cross_tick(&short, 60, Some("FE")), None);
    }

    #[test]
    fn off_line_crossing_outside_radius_does_not_count() {
        // Crossing the gate's Y but 200 units off to the side (outside the
        // 90.5 plane radius) must not register.
        let mut v = Vec::new();
        for i in 0..100 {
            v.push([519.2 + 200.0, -1401.6 + 0.5 * (i as f32), 53.6]);
        }
        assert_eq!(start_cross_tick(&v, 100, Some("FE")), None);
    }

    #[test]
    fn all_nine_tracks_have_points() {
        for code in ["FE", "FM", "FH", "AE", "AM", "AH", "VE", "VM", "VH"] {
            assert!(
                START_POINTS.iter().any(|(c, p)| *c == code && !p.is_empty()),
                "missing start point for {}",
                code
            );
        }
    }
}
