/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  showWindow: () => __TAURI_INVOKE<void>("show_window"),
  runInject: (trainerSettings: TrainerSettings) => __TAURI_INVOKE<string>("run_inject", { trainerSettings }),
  readRdConfig: () => __TAURI_INVOKE<string>("read_rd_config"),
  writeRdConfig: (rdConfig: RdConfig) => __TAURI_INVOKE<null>("write_rd_config", { rdConfig }),
  openLogFile: () => __TAURI_INVOKE<null>("open_log_file"),
  openPlayerTypes: () => __TAURI_INVOKE<null>("open_player_types"),
  closeOthers: () => __TAURI_INVOKE<null>("close_others"),
  getLogData: () => __TAURI_INVOKE<string[]>("get_log_data"),
  writeLanguage: (language: string) => __TAURI_INVOKE<null>("write_language", { language }),
  writeDetailConfig: (detailConfig: DetailConfig) => __TAURI_INVOKE<null>("write_detail_config", { detailConfig }),
  readDetailConfig: () => __TAURI_INVOKE<([string, string])[]>("read_detail_config"),
  setFirstPlayerType: (character: string) => __TAURI_INVOKE<null>("set_first_player_type", { character }),
  getFirstPlayerType: () => __TAURI_INVOKE<string>("get_first_player_type"),
  checkForUpdates: (force: boolean) => __TAURI_INVOKE<UpdateInfo>("check_for_updates", { force }),
  downloadAndExtract: (url: string, onEvent: Channel<DownloadEvent>) => __TAURI_INVOKE<DownloadResult>("download_and_extract", { url, onEvent }),
  cancelDownload: (id: string) => __TAURI_INVOKE<boolean>("cancel_download", { id }),
  getVersion: () => __TAURI_INVOKE<string>("get_version"),
  relaunch: () => __TAURI_INVOKE<void>("relaunch"),
  logStartupTime: (startupTimeInfo: StartupTimeInfo) => __TAURI_INVOKE<string>("log_startup_time", { startupTimeInfo }),
  killExit1: () => __TAURI_INVOKE<string>("kill_exit_1"),
};

/* Types */
export type DetailConfig = {
  renderDistance: number | null,
  groundDetail: number | null,
};

export type DownloadEvent = { event: "downloadProgress"; data: {
  progress: number,
  progressTotal: number,
  total: number,
  transferSpeed: number,
} } | { event: "token"; data: {
  token: string,
} } | { event: "downloadCancelled" };

export type DownloadResult = {
  installed: boolean,
};

export type RdConfig = {
  apiName: string,
  width: number,
  height: number,
  depth: number,
  cardId: number,
  fullscreen: boolean,
};

export type StartupTimeInfo = {
  onMounted1: number | null,
  onMounted2: number | null,
  createAppTime: number | null,
  mountAppTime: number | null,
  registerPluginsTime: number | null,
  totalStartupTime: number | null,
};

export type TrainerSettings = {
  use4xFonts: boolean,
  changeFov: boolean,
  fovWidth: number | null,
  fovHeight: number | null,
  enableLogging: boolean,
  makeGhostsOpaque: boolean,
  matchGhostSoundsToCharacter: boolean,
  disableDirectInput: boolean,
  enableCustomControls: boolean,
  hideBlinkingR: boolean,
  showReplaySpeed: boolean,
};

export type UpdateInfo = {
  currentVersion: string,
  latestVersion: string,
};

