/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
    Autostart: typeof import('./src/components/Autostart.vue')['default']
    DisableDirectInputTooltip: typeof import('./src/components/DisableDirectInputTooltip.vue')['default']
    DownloadLatestButton: typeof import('./src/components/DownloadLatestButton.vue')['default']
    EnableLoggingTooltip: typeof import('./src/components/EnableLoggingTooltip.vue')['default']
    ErrorDialog: typeof import('./src/components/ErrorDialog.vue')['default']
    FovSelectorRow: typeof import('./src/components/FovSelectorRow.vue')['default']
    GhostSoundsTooltip: typeof import('./src/components/GhostSoundsTooltip.vue')['default']
    LanguageSelect: typeof import('./src/components/LanguageSelect.vue')['default']
    RenderDistanceRow: typeof import('./src/components/RenderDistanceRow.vue')['default']
    RenderOptions: typeof import('./src/components/RenderOptions.vue')['default']
    SettingsButton: typeof import('./src/components/SettingsButton.vue')['default']
    TrainerOptions: typeof import('./src/components/TrainerOptions.vue')['default']
    UpdateDialog: typeof import('./src/components/UpdateDialog.vue')['default']
  }
}
