set shell := ["pwsh.exe", "-NoProfile", "-c", "$ErrorActionPreference = 'Stop'; $PSNativeCommandUseErrorActionPreference = $true;"]
set unstable

dc_profile := 'release'

all: clean _build

[private]
[parallel]
_build: display_config display_config_helper

display_config:
    cd Display_Config && bun tauri build {{ if dc_profile == "debug" { "--debug" } else { "" } }} -- --locked;
    New-Item -ItemType Directory -Force ./output | Out-Null; \
    cp Display_Config\src-tauri\target\{{dc_profile}}\display-config.exe ./output/Display_Config.exe

display_config_helper:
    $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath; \
    $msbuild = "$vsPath\MSBuild\Current\Bin\MSBuild.exe"; \
    rm -Force -Recurse .\Display_Config_Resources\Display_Config_Helper\Release -ErrorAction SilentlyContinue; \
    & $msbuild .\Display_Config_Resources\Display_Config_Helper\Display_Config_Helper.vcxproj /v:minimal /p:Configuration=Release; \
    & $msbuild .\Display_Config_Resources\Injector\Injector.vcxproj /v:minimal /p:Configuration=Release; \

    New-Item -ItemType Directory -Force ./output | Out-Null; \
    New-Item -ItemType Directory -Force ./output/Display_Config_Resources | Out-Null; \
    cp .\Display_Config_Resources\Display_Config_Helper\Release\Display_Config_Helper.dll ./output/Display_Config_Resources/; \
    cp .\Display_Config_Resources\Injector\Release\Injector.exe ./output/Display_Config_Resources/

clean:
    if (Test-Path .\output) { Remove-Item .\output -Recurse -Force }
