on:
  pull_request:
  push: # Run CI on the main branch after every merge. This is important to fill the GitHub Actions cache in a way that pull requests can see it
    branches:
      - main
name: ci
jobs:
  analyzeLint:
    name: analyze:lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd analyze && bun install
      - run: cd analyze && bun run lint
      - run: cd analyze && bun run typecheck
  analyzeTest:
    name: analyze:test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd analyze && bun install
      - run: cd analyze && bun run test
  threejsLint:
    name: threejs:lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd threejs && bun install
      - run: cd threejs && bun run lint
      - run: cd threejs && bun run typecheck
  displayConfigBuild:
    name: displayConfig:build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd Display_Config/Display_Config && bun install
      - run: cd Display_Config/Display_Config && bun tauri build --debug
  displayConfigBindings:
    name: displayConfig:bindings
    runs-on: windows-latest
    env:
      BINDINGS_PATH: "Display_Config/Display_Config/src/bindings.ts"
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd Display_Config/Display_Config && bun install
      - run: cd Display_Config/Display_Config/src-tauri && cargo run --bin codegen
      - name: Check if bindings.ts exists
        run: |
          if [ ! -f "${{ env.BINDINGS_PATH }}" ]; then
            echo "ERROR: bindings.ts does not exist at ${{ env.BINDINGS_PATH }}"
            exit 1
          fi
        shell: bash
      - name: Check if bindings.ts is unchanged
        run: |
          git diff --color HEAD -- "${{ env.BINDINGS_PATH }}"
          if [ $? -ne 0 ] || [ -n "$(git diff HEAD -- "${{ env.BINDINGS_PATH }}")" ]; then
            echo "bindings.ts has been modified"
            exit 1
          fi
        shell: bash
  displayConfigLintRust:
    name: displayConfig:lintRust
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd Display_Config/Display_Config/src-tauri && cargo fmt --all --check
      - run: cd Display_Config/Display_Config/src-tauri && cargo clippy -- -Dwarnings
  displayConfigTestRust:
    name: displayConfig:testRust
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd Display_Config/Display_Config/src-tauri && cargo test
  displayConfigLintVue:
    name: displayConfig:lintVue
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd Display_Config/Display_Config && bun install
      - run: cd Display_Config/Display_Config && bun run lint
      - run: cd Display_Config/Display_Config && bun run typecheck
  displayConfigTest:
    name: displayConfig:test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: cd Display_Config/Display_Config && bun install
      - run: cd Display_Config/Display_Config && bun run test
  displayConfigCppBuild:
    name: displayConfig:cppBuild
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: ilammy/msvc-dev-cmd@v1.4.1
        with:
          arch: win32
      - uses: extractions/setup-just@v3
      - uses: arduino/setup-task@v2
      - run: cd Display_Config/Display_Config && bun install
      - run: cd Display_Config/Display_Config && just
